#!/bin/bash

set -e

cd vendor/cmark/cmark
make
cd -
find -E vendor/cmark/cmark -type f -iregex '.*\.(c|h|inc|re)' | xargs -I{} cp {} vendor/cmark
sed -i '' '/#define HAVE___BUILTIN_EXPECT/d' vendor/cmark/config.h
