name: Upload Prebuild Binaries

on:
  release:
    types: [created]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn
      - name: Prebuild binaries
        run: yarn prebuild:all
      - name: Upload binaries
        run: yarn upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
